name: stackoverflow_users
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  http: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.2
  riverpod: ^2.4.9
  shared_preferences: ^2.2.3
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.png"
  android: true
  ios: true

  android_12:
    image: "assets/logo.png"
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
